name: wc_flutter_share_example
description: Demonstrates how to use the wc_flutter_share plugin.

publish_to: 'none'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  wc_flutter_share:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/wisecrab.png
